version: 2

sources:
  - name: data
    schema: gz_raw_data
    description: data from gz
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales information about each product and order
      - name: product
        identifier: raw_gz_product
        description: details about each product
      - name: ship
        identifier: raw_gz_ship
        description: details about shipping per order
