version: 2

sources:
  - name: gz_raw_data
    schema: raw
    description: data from Circle
    tables:
      - name: raw_gz_sales
        identifier: sales
        description: sales information about each product and order
      - name: raw_gz_product
        identifier: product
        description: details about each product
      - name: raw_gz_ship
        identifier: ship
        description: details about shipping per order
